version: "3.7"

services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    entrypoint: rq worker --url redis://redis:6379

  database:
    restart: "no"
    image: postgres:latest
    env_file: devops/env_files/database.conf
    ports:
      - '5432:5432'

  cyclops:
    build:
      context: .
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@database/cyclops_db
    ports:
      - "5000:5000"
    depends_on:
      - database
      - redis
