version: 2.1

references:
  working_directory: &working_directory ~/cyclops

  set_env_variables: &set_env_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}

  build_cyclops_image: &build_cyclops_image
    run:
      name: Build and Tag Cyclops Image
      command: |
        docker build -t mwangik/cyclops:latest

  tag_cyclops_image: &tag_cyclops_image
    run:
      name: Tag Image
      command: |
        docker tag mwangik/cyclops:latest mwangik/cyclops:${CIRCLE_SHA1}
        docker tag mwangik/cyclops:latest mwangik/cyclops:${CIRCLE_BRANCH}

  push_cyclops_image: &push_cyclops_image
    run:
      name: Push Cyclops Image
      command: docker push mwangik/cyclops:${CIRCLE_SHA1}
      if [ "${CIRCLE_BRANCH}" == "main" ]
      then
        docker push mwangik/cyclops:latest
      else:
        docker push mwangik/cyclops:${CIRCLE_BRANCH}
      fi

  run_unit_tests: &run_unit_tests
    run:
      name: Run Unit Tests
      command: |
        docker-compose -f tests/docker-compose.yml run tests-unit

  run_integration_tests: &run_integration_tests
    run:
      name: Run Integration Tests
      command: |
        docker-compose -f tests/docker-compose.yml run tests-integration